#!/usr/bin/env bash
#  configures a server
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
NGINX_PID=$(pgrep -u root nginx)
echo "$NGINX_PID" > /run/nginx.pid
service nginx reload
