#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 100.
for((b=1;b<=100;b++))
do
    if ((b % 15 == 0))
    then
        echo "FizzBuzz"
    elif ((b % 3 == 0))
    then
        echo "Fizz"
    elif ((b % 5 == 0))
    then
        echo "Buzz"
    else
        echo "$b"
    fi
done
