#!/usr/bin/env bash
# Bash Shell with multiple condition statements
b=1
while [ $b -le 10 ]
do
    if [ $b -eq 8 ]
	then
		echo "good luck"
    elif [ $b -eq 4 ]
    then
        echo "bad luck"
    else
	    echo "Best School"
	fi
	((b=b+1))
done
