#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20 with exceptions
b=1
while ((b < 21))
do
	echo $b
	case "$b" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	((b++))
done
