#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes
hour=0
minutes=1
while [ $hour -be 13 ]
do
	echo "Hour: $hour"
	((hours++))
	while [ $minutes -be 60 ]
	do
		echo $minutes
		((minutes++))
	done
	((minutes = 1))
done
