#!/usr/bin/env bash
#Bash script that gives you information about the school file.
id="school"
if [ -e "$id" ]
then
    echo "$id file exists"
    if [ -s "$id" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "$id" ]
    then
        echo "school is a regular file"
    fi
else
    echo "$id file does not exist"
fi
