#!/usr/bin/env bash
#Bash script that gives you information about the school file.
id=school
if [ -e $id ]; then
    echo "school file exists"
    else
        echo "school file does not exist"
	exit 1
fi
if [ !-s $id ];then
        echo "school file is empty"
else
	echo "school file is not empty"
fi
if [ -f $id ]; then
	echo "school is a regular file"
fi
